#!/usr/bin/env python3
"""
FEP ΔΔG_binding Analysis - MBAR Method with Visualization

Directory structure (generated by setup_fep.sh + submit_fep.sh):

    <base_path>/
    ├── forward/
    │   ├── bound_R1/lambda{0..31}/PROD/prod.xvg
    │   ├── bound_R2/lambda{0..31}/PROD/prod.xvg
    │   ├── bound_R3/lambda{0..31}/PROD/prod.xvg
    │   ├── unbound_R1/lambda{0..31}/PROD/prod.xvg
    │   ├── unbound_R2/lambda{0..31}/PROD/prod.xvg
    │   └── unbound_R3/lambda{0..31}/PROD/prod.xvg
    └── reverse/          [optional; improves MBAR accuracy when available]
        ├── bound_R{1..N}/lambda{0..31}/PROD/prod.xvg
        └── unbound_R{1..N}/lambda{0..31}/PROD/prod.xvg

Forward vs Reverse in HREX-FEP (NOT non-equilibrium FEP):
  - HREX-FEP: each window runs at a FIXED lambda; lambda does NOT change during simulation.
  - Forward: 32 windows at lambda=0..1, starting structures taken from HIS-end conformation.
  - Reverse: same 32 windows at the SAME lambda=0..1, but starting structures taken from the
    ARG-end conformation (last frame of forward lambda31).
  - Both directions compute ΔG(HIS→ARG). MBAR result: fwd ≈ rev, SAME sign.
  - Combining fwd+rev samples improves sampling: fwd seeds HIS-like conformations (good low-λ),
    rev seeds ARG-like conformations (good high-λ). Together reduces systematic sampling gaps.
  - Convergence check: |ΔG_fwd - ΔG_rev| should be < 1-2 kJ/mol.
  [Contrast: BAR with non-equilibrium switching DOES give ΔG_rev = -ΔG_fwd; that is a
   different technique and does NOT apply here.]

Usage:
    python analyze_fep.py /path/to/outputs/design_name
    python analyze_fep.py /path/to/outputs/design_name --skip 0.2
    python analyze_fep.py /path/to/outputs/design_name --no-plots
"""

import os
import sys
import argparse
import warnings
import logging
import re

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

warnings.filterwarnings('ignore')
logging.basicConfig(level=logging.CRITICAL)
for _lg in ['alchemlyb', 'pymbar', 'alchemlyb.estimators', 'pymbar.mbar',
            'alchemlyb.preprocessing', 'alchemlyb.preprocessing.subsampling',
            'alchemlyb.estimators.mbar']:
    logging.getLogger(_lg).setLevel(logging.CRITICAL)
# alchemlyb uses loguru for debug output — disable it entirely
try:
    from loguru import logger as _loguru_logger
    _loguru_logger.disable('alchemlyb')
except ImportError:
    pass

from alchemlyb.parsing.gmx import extract_u_nk
from alchemlyb.preprocessing import subsampling
from alchemlyb.estimators import MBAR
from alchemlyb.visualisation import plot_mbar_overlap_matrix

# Physical constants
R_KJ = 8.314e-3   # kJ/(mol·K)

# Defaults (overridable via CLI)
TEMPERATURE   = 310
SKIP_FRACTION = 0.1
N_WINDOWS     = 32
MAX_REPLICAS  = 5

# ──────────────────────────────────────────────────────────────────────────────
# Data discovery & loading
# ──────────────────────────────────────────────────────────────────────────────

def find_dhdl_files(base_path, direction, state, n_windows, max_replicas):
    """Find prod.xvg (or dhdl.xvg) for every lambda window across all replicas.

    Actual path: <base_path>/<direction>/<state>_R<n>/lambda<w>/PROD/prod.xvg

    Returns:
        list of (replica_id, window_idx, absolute_file_path)
    """
    found = []
    for replica in range(1, max_replicas + 1):
        state_dir = os.path.join(base_path, direction, f"{state}_R{replica}")
        if not os.path.isdir(state_dir):
            continue
        for win in range(n_windows):
            # Priority: PROD/prod.xvg → PROD/dhdl.xvg → dhdl.xvg (fallback)
            candidates = [
                os.path.join(state_dir, f"lambda{win}", "PROD", "prod.xvg"),
                os.path.join(state_dir, f"lambda{win}", "PROD", "dhdl.xvg"),
                os.path.join(state_dir, f"lambda{win}", "dhdl.xvg"),
            ]
            for fpath in candidates:
                if os.path.isfile(fpath) and os.path.getsize(fpath) > 0:
                    found.append((replica, win, fpath))
                    break
    return found


def load_u_nk_from_files(file_entries, T, skip_frac, label=""):
    """Load, trim equilibration, and decorrelate u_nk from file list.

    Args:
        file_entries: list of (replica, win, path)
    Returns:
        concatenated u_nk DataFrame, or None on total failure
    """
    u_nk_list = []
    n_ok = n_fail = 0
    failed_ids = []
    for replica, win, fpath in file_entries:
        try:
            u_nk = extract_u_nk(fpath, T=T)
            if len(u_nk) > 100:
                u_nk = u_nk.iloc[int(len(u_nk) * skip_frac):]
            u_nk = subsampling.decorrelate_u_nk(u_nk)
            u_nk_list.append(u_nk)
            n_ok += 1
        except Exception as e:
            failed_ids.append(f"R{replica}/lambda{win}")
            n_fail += 1

    if label:
        status = f"{n_ok}/{len(file_entries)} windows OK"
        if n_fail:
            status += f", {n_fail} FAILED: {', '.join(failed_ids[:5])}"
            if len(failed_ids) > 5:
                status += f" (+{len(failed_ids)-5} more)"
        print(f"    {label}: {status}")
    return pd.concat(u_nk_list) if u_nk_list else None


def load_state_data(base_path, state, n_windows, max_replicas, skip_frac, T):
    """Load u_nk for one thermodynamic state across all replicas and directions.

    Returns:
        (u_nk_fwd, u_nk_rev)  — u_nk_rev is None when reverse runs not available
    """
    fwd_files = find_dhdl_files(base_path, 'forward', state, n_windows, max_replicas)
    rev_files = find_dhdl_files(base_path, 'reverse', state, n_windows, max_replicas)

    n_fwd_rep = len(set(r for r, _, _ in fwd_files))
    rev_note  = (f"{len(rev_files)} files ({len(set(r for r,_,_ in rev_files))} rep)"
                 if rev_files else "none")
    print(f"  {state.upper():8s}  fwd: {len(fwd_files)} files ({n_fwd_rep} rep)  "
          f"rev: {rev_note}")

    u_nk_fwd = load_u_nk_from_files(fwd_files, T, skip_frac, label="    fwd") \
               if fwd_files else None
    u_nk_rev = load_u_nk_from_files(rev_files, T, skip_frac, label="    rev") \
               if rev_files else None

    return u_nk_fwd, u_nk_rev


def extract_final_ddg_line(results_path):
    try:
        with open(results_path, encoding='utf-8') as handle:
            for line in handle:
                if 'ΔΔG_binding (final)' in line:
                    return line.strip()
    except Exception:
        return '(see file)'
    return '(see file)'


def find_outer_replicas(outputs_root):
    replica_ids = []
    for name in os.listdir(outputs_root):
        match = re.fullmatch(r'replica(\d+)', name)
        if not match:
            continue
        rep_dir = os.path.join(outputs_root, name)
        if os.path.isdir(rep_dir):
            replica_ids.append(int(match.group(1)))
    return sorted(replica_ids)


def summary_sort_key(label):
    match = re.fullmatch(r'replica(\d+)/(.*)', label)
    if match:
        return (int(match.group(1)), match.group(2))
    return (10**9, label)


def split_label(label):
    match = re.fullmatch(r'(replica\d+)/(.*)', label)
    if match:
        return match.group(1), match.group(2)
    return '', label


def parse_final_ddg_values(result_line):
    if not result_line:
        return None

    full_match = re.search(
        r'ΔΔG_binding \(final\)\s*=\s*([+-]?\d+(?:\.\d+)?)\s*±\s*([+-]?\d+(?:\.\d+)?)\s*kJ/mol'
        r'\s*\(\s*([+-]?\d+(?:\.\d+)?)\s*±\s*([+-]?\d+(?:\.\d+)?)\s*kcal/mol\s*\)',
        result_line,
    )
    if full_match:
        kJ = float(full_match.group(1))
        err_kJ = abs(float(full_match.group(2)))
        kcal = float(full_match.group(3))
        err_kcal = abs(float(full_match.group(4)))
        return {'kJ': kJ, 'err_kJ': err_kJ, 'kcal': kcal, 'err_kcal': err_kcal}

    kj_only = re.search(
        r'ΔΔG_binding \(final\)\s*=\s*([+-]?\d+(?:\.\d+)?)\s*±\s*([+-]?\d+(?:\.\d+)?)\s*kJ/mol',
        result_line,
    )
    if not kj_only:
        return None

    kJ = float(kj_only.group(1))
    err_kJ = abs(float(kj_only.group(2)))
    kcal = kJ / 4.184
    err_kcal = err_kJ / 4.184
    return {'kJ': kJ, 'err_kJ': err_kJ, 'kcal': kcal, 'err_kcal': err_kcal}


def build_csv_row(label, result_line):
    design_group, design_name = split_label(label)
    parsed = parse_final_ddg_values(result_line)
    row = {
        'design_group': design_group,
        'Design': design_name,
        'ΔΔG (kcal/mol)': '',
        'Error (kcal/mol)': '',
        'ΔΔG (kJ/mol)': '',
        'Error (kJ/mol)': '',
    }
    if parsed is None:
        return row

    row['ΔΔG (kcal/mol)'] = f"{parsed['kcal']:.3f}"
    row['Error (kcal/mol)'] = f"±{parsed['err_kcal']:.3f}"
    row['ΔΔG (kJ/mol)'] = f"{parsed['kJ']:.3f}"
    row['Error (kJ/mol)'] = f"±{parsed['err_kJ']:.3f}"
    return row


def update_batch_summary_table(outputs_root, records):
    summary_tsv_path = os.path.join(outputs_root, 'ddg_analysis_summary.tsv')
    summary_csv_path = os.path.join(outputs_root, 'ddg_analysis_summary.csv')

    # Keep a detailed machine-readable table for script-side state merging.
    rows_by_label = {}
    if os.path.isfile(summary_tsv_path):
        try:
            existing = pd.read_csv(summary_tsv_path, sep='\t', dtype=str).fillna('')
            for row in existing.to_dict('records'):
                label = row.get('label', '').strip()
                if label:
                    rows_by_label[label] = row
        except Exception as exc:
            print(f"WARNING: could not read existing summary table {summary_tsv_path}: {exc}")

    for record in records:
        rows_by_label[record['label']] = record

    merged_rows = [rows_by_label[label] for label in sorted(rows_by_label, key=summary_sort_key)]
    pd.DataFrame(merged_rows, columns=['label', 'status', 'result', 'design_path']).to_csv(
        summary_tsv_path, sep='\t', index=False, encoding='utf-8'
    )

    # Write user-facing CSV in the requested format.
    csv_rows_by_label = {}
    if os.path.isfile(summary_csv_path):
        try:
            existing_csv = pd.read_csv(summary_csv_path, dtype=str).fillna('')
            for row in existing_csv.to_dict('records'):
                group = row.get('design_group', '').strip()
                design = row.get('Design', '').strip()
                if group and design:
                    csv_rows_by_label[f"{group}/{design}"] = {
                        'design_group': group,
                        'Design': design,
                        'ΔΔG (kcal/mol)': row.get('ΔΔG (kcal/mol)', ''),
                        'Error (kcal/mol)': row.get('Error (kcal/mol)', ''),
                        'ΔΔG (kJ/mol)': row.get('ΔΔG (kJ/mol)', ''),
                        'Error (kJ/mol)': row.get('Error (kJ/mol)', ''),
                    }
        except Exception as exc:
            print(f"WARNING: could not read existing summary csv {summary_csv_path}: {exc}")

    # Refresh CSV rows from the merged detailed table to keep them in sync.
    for label, row in rows_by_label.items():
        csv_rows_by_label[label] = build_csv_row(label, row.get('result', ''))

    ordered_labels = sorted(csv_rows_by_label, key=summary_sort_key)
    csv_rows = [csv_rows_by_label[label] for label in ordered_labels]
    pd.DataFrame(
        csv_rows,
        columns=[
            'design_group',
            'Design',
            'ΔΔG (kcal/mol)',
            'Error (kcal/mol)',
            'ΔΔG (kJ/mol)',
            'Error (kJ/mol)',
        ],
    ).to_csv(summary_csv_path, index=False, encoding='utf-8-sig')

    print(f"Summary table saved: {summary_tsv_path}")
    print(f"Summary CSV saved: {summary_csv_path}")


# ──────────────────────────────────────────────────────────────────────────────
# MBAR calculation
# ──────────────────────────────────────────────────────────────────────────────

def calc_mbar(u_nk_fwd, u_nk_rev, T):
    """Fit MBAR separately for forward-only, reverse-only, and combined data.

    IMPORTANT - HREX-FEP forward/reverse convention:
      Both forward and reverse use the SAME lambda schedule (0→1, HIS→ARG).
      'Reverse' differs only in starting conformation (ARG-end frame), NOT in lambda direction.
      Therefore: fwd ΔG ≈ rev ΔG with the SAME sign.  This is correct and expected.
      A large |ΔG_fwd - ΔG_rev| indicates insufficient convergence (not a sign error).

    This is fundamentally different from BAR non-equilibrium FEP, where reverse work
    values give ΔG_rev = -ΔG_fwd. That convention does NOT apply to HREX-FEP + MBAR.

    Combined (fwd+rev) gives the lowest-uncertainty estimate and is returned.
    MBAR output delta_f_ is in kT; converted to kJ/mol by multiplying by R*T.

    Returns:
        (dG_kJmol, err_kJmol, mbar_obj)  — from combined fit (or fwd-only if no rev)
    """
    if u_nk_fwd is None:
        return None, None, None, None, None, None, None

    kBT = R_KJ * T

    def _fit(u_nk):
        m = MBAR()
        m.fit(u_nk)
        dg  = float(m.delta_f_.iloc[0, -1])  * kBT
        err = float(m.d_delta_f_.iloc[0, -1]) * kBT
        return dg, err, m

    dG_f, err_f, mbar_f = _fit(u_nk_fwd)
    print(f"    fwd-only : ΔG = {dG_f:+.2f} ± {err_f:.2f} kJ/mol  ({len(u_nk_fwd)} samples)")

    if u_nk_rev is not None:
        dG_r, err_r, _      = _fit(u_nk_rev)
        print(f"    rev-only : ΔG = {dG_r:+.2f} ± {err_r:.2f} kJ/mol  ({len(u_nk_rev)} samples)")
        combined            = pd.concat([u_nk_fwd, u_nk_rev])
        dG_c, err_c, mbar_c = _fit(combined)
        print(f"    combined : ΔG = {dG_c:+.2f} ± {err_c:.2f} kJ/mol  ({len(combined)} samples)  ← used")
        return dG_f, err_f, dG_r, err_r, dG_c, err_c, mbar_c
    else:
        return dG_f, err_f, None, None, dG_f, err_f, mbar_f


# ──────────────────────────────────────────────────────────────────────────────
# Plotting
# ──────────────────────────────────────────────────────────────────────────────

def plot_overlap_matrix(mbar, output_path, title):
    try:
        ax = plot_mbar_overlap_matrix(mbar.overlap_matrix)
        ax.set_title(title, fontsize=13, fontweight='bold')
        ax.figure.savefig(output_path, dpi=300, bbox_inches='tight')
        plt.close(ax.figure)
        print(f"  Saved: {output_path}")
    except Exception as e:
        print(f"  WARNING: overlap matrix plot failed: {e}")


def plot_free_energy_profile(mbar, T, output_path, title):
    """Plot ΔF profile in kJ/mol (converting from kT stored in mbar)."""
    try:
        kBT = R_KJ * T
        free_energies = mbar.delta_f_.iloc[0, :] * kBT
        errors        = mbar.d_delta_f_.iloc[0, :] * kBT
        n = len(free_energies)

        fig, ax = plt.subplots(figsize=(10, 6))
        ax.errorbar(range(n), free_energies, yerr=errors,
                    marker='o', markersize=7, linewidth=2, capsize=4,
                    color='#2E86AB', ecolor='#A23B72', capthick=2)
        ax.set_title(title, fontsize=13, fontweight='bold')
        ax.set_xlabel('Lambda state index', fontsize=12)
        ax.set_ylabel('ΔF (kJ/mol)', fontsize=12)
        ax.set_xticks(range(0, n, max(1, n // 8)))
        ax.grid(alpha=0.3, linestyle='--')
        ax.axhline(y=0, color='gray', linestyle='--', linewidth=1)
        fig.tight_layout()
        fig.savefig(output_path, dpi=300, bbox_inches='tight')
        plt.close(fig)
        print(f"  Saved: {output_path}")
    except Exception as e:
        print(f"  WARNING: free energy profile plot failed: {e}")
        import traceback; traceback.print_exc()


def plot_convergence(u_nk_fwd, u_nk_rev, output_path, title):
    try:
        n_fwd = len(u_nk_fwd)
        n_rev = len(u_nk_rev) if u_nk_rev is not None else 0

        fig, axes = plt.subplots(1, 2, figsize=(12, 5))

        # Panel 1: sample counts
        if n_rev > 0:
            labels = ['Forward', 'Reverse', 'Total']
            counts = [n_fwd, n_rev, n_fwd + n_rev]
            colors = ['#2E86AB', '#A23B72', '#44803F']
        else:
            labels = ['Forward (only)', 'Total']
            counts = [n_fwd, n_fwd]
            colors = ['#2E86AB', '#44803F']

        bars = axes[0].bar(labels, counts, color=colors, alpha=0.8, edgecolor='black')
        axes[0].set_ylabel('Decorrelated samples')
        axes[0].set_title('Sample statistics')
        axes[0].grid(alpha=0.3, linestyle='--', axis='y')
        for bar, cnt in zip(bars, counts):
            axes[0].text(bar.get_x() + bar.get_width() / 2, bar.get_height(),
                         str(cnt), ha='center', va='bottom', fontsize=10, fontweight='bold')

        # Panel 2: fwd/rev ratio
        ratio = n_fwd / n_rev if n_rev > 0 else float('inf')
        display_ratio = min(ratio, 5.0)
        axes[1].bar(['Fwd/Rev\nratio'], [display_ratio],
                    color='#F18F01', alpha=0.8, edgecolor='black')
        axes[1].axhline(1.0, color='green', linestyle='--', linewidth=2, label='Ideal: 1.0')
        axes[1].set_ylim(0, max(3.0, display_ratio * 1.2))
        axes[1].set_title('Forward/Reverse balance')
        axes[1].legend()
        note = f'{ratio:.2f}' if ratio != float('inf') else 'fwd only'
        axes[1].text(0, display_ratio, note,
                     ha='center', va='bottom', fontsize=11, fontweight='bold')

        fig.suptitle(title, fontsize=13, fontweight='bold')
        fig.tight_layout()
        fig.savefig(output_path, dpi=300, bbox_inches='tight')
        plt.close(fig)
        print(f"  Saved: {output_path}")
    except Exception as e:
        print(f"  WARNING: convergence plot failed: {e}")


# ──────────────────────────────────────────────────────────────────────────────
# Batch helpers
# ──────────────────────────────────────────────────────────────────────────────

def is_analysis_done(design_dir):
    """Return True if ddG_results.txt already exists (analysis complete)."""
    return os.path.isfile(os.path.join(design_dir, 'ddG_results.txt'))


def find_designs_with_data(outputs_root):
    """Scan outputs/replicaN/<design>/ and return those containing any .xvg file.

    Returns list of (label, abs_design_path) sorted by replica then design name.
    """
    results = []
    for rep_n in find_outer_replicas(outputs_root):
        rep_dir = os.path.join(outputs_root, f"replica{rep_n}")
        for name in sorted(os.listdir(rep_dir)):
            design_dir = os.path.join(rep_dir, name)
            if not os.path.isdir(design_dir):
                continue
            has_data = any(
                fname.endswith('.xvg')
                for _, _, files in os.walk(design_dir)
                for fname in files
            )
            if has_data:
                results.append((f"replica{rep_n}/{name}", os.path.abspath(design_dir)))
    return results


# ──────────────────────────────────────────────────────────────────────────────
# Single-design analysis
# ──────────────────────────────────────────────────────────────────────────────

def analyze_one(base_path, args):
    """Run full \u0394\u0394G analysis for one design directory.  Returns True on success."""
    print("=" * 70)
    print(f"FEP \u0394\u0394G Analysis  |  {base_path}")
    print(f"T = {args.temp} K  |  skip {args.skip*100:.0f}%  |  "
          f"{args.windows} windows  |  max {args.replicas} replicas")
    print("=" * 70)

    # ── Load data ──────────────────────────────────────────────────────────────
    print("\nLoading data...")
    u_b_f, u_b_r = load_state_data(base_path, 'bound',
                                    args.windows, args.replicas, args.skip, args.temp)
    u_u_f, u_u_r = load_state_data(base_path, 'unbound',
                                    args.windows, args.replicas, args.skip, args.temp)

    if u_b_f is None:
        print("ERROR: No BOUND forward data. Check directory structure.")
        return False
    if u_u_f is None:
        print("ERROR: No UNBOUND forward data. Check directory structure.")
        return False

    # ── MBAR ───────────────────────────────────────────────────────────────────
    print("\nFitting MBAR...")
    print("  [HREX-FEP: fwd and rev both compute \u0394G(HIS\u2192ARG); expect fwd \u2248 rev (SAME sign, same magnitude)]")
    print("  [convergence check: |\u0394G_fwd - \u0394G_rev| should be < 1-2 kJ/mol]")
    print("  BOUND state:")
    dG_b_f, err_b_f, dG_b_r, err_b_r, dG_b, err_b, mbar_b = calc_mbar(u_b_f, u_b_r, args.temp)

    print("  UNBOUND state:")
    dG_u_f, err_u_f, dG_u_r, err_u_r, dG_u, err_u, mbar_u = calc_mbar(u_u_f, u_u_r, args.temp)

    if dG_b is None or dG_u is None:
        print("\nERROR: MBAR calculation failed.")
        return False

    ddG_f    = dG_b_f - dG_u_f
    err_f_v  = np.sqrt(err_b_f**2 + err_u_f**2)
    ddG      = dG_b   - dG_u
    err      = np.sqrt(err_b**2   + err_u**2)
    if has_rev:
        ddG_r   = dG_b_r - dG_u_r
        err_r_v = np.sqrt(err_b_r**2 + err_u_r**2)

    def _row(dGb, eb, dGu, eu, ddg, ed):
        return (f"  {dGb:+9.2f} \u00b1 {eb:.2f}    {dGu:+9.2f} \u00b1 {eu:.2f}    {ddg:+7.2f} \u00b1 {ed:.2f}")

    print("\n" + "=" * 70)
    if has_rev:
        print("FINAL RESULTS  (MBAR)")
    else:
        print("FINAL RESULTS  (MBAR \u2014 forward only)")
    print("=" * 70)
    _h1 = "\u0394G_bound (kJ/mol)"; _h2 = "\u0394G_unbound (kJ/mol)"; _h3 = "\u0394\u0394G_binding (kJ/mol)"
    print(f"  {'':11s}  {_h1:^18s}   {_h2:^18s}   {_h3:^18s}")
    print("-" * 70)
    print(f"  fwd-only :" + _row(dG_b_f, err_b_f, dG_u_f, err_u_f, ddG_f, err_f_v))
    if has_rev:
        print(f"  rev-only :" + _row(dG_b_r, err_b_r, dG_u_r, err_u_r, ddG_r, err_r_v))
        print(f"  combined :" + _row(dG_b, err_b, dG_u, err_u, ddG, err) + "  \u2190 final")
    print("=" * 70)

    if has_rev:
        conv = abs(ddG_f - ddG_r)
        conv_note = "OK" if conv <= 2.0 else "WARNING: consider more sampling"
        print(f"\n  Convergence |\u0394\u0394G_fwd \u2212 \u0394\u0394G_rev| = {conv:.2f} kJ/mol  [{conv_note}]")

    final_ddG = ddG
    if   final_ddG >  2.0:
        print(f"\n  \u0394\u0394G = {final_ddG:+.1f} kJ/mol  \u2192 Mutation WEAKENS binding")
    elif final_ddG < -2.0:
        print(f"\n  \u0394\u0394G = {final_ddG:+.1f} kJ/mol  \u2192 Mutation STRENGTHENS binding")
    else:
        print(f"\n  \u0394\u0394G \u2248 {final_ddG:+.1f} kJ/mol  \u2192 No significant effect (within \u00b12 kJ/mol)")

    # ── Save results ───────────────────────────────────────────────────────────
    out_file = os.path.join(base_path, 'ddG_results.txt')
    with open(out_file, 'w', encoding='utf-8') as f:
        f.write("FEP \u0394\u0394G_binding Analysis Results (MBAR)\n")
        f.write("=" * 70 + "\n\n")
        f.write(f"Directory:   {base_path}\n")
        f.write(f"Temperature: {args.temp} K\n")
        f.write(f"Skip:        {args.skip:.1%}\n")
        f.write(f"kBT:         {R_KJ * args.temp:.4f} kJ/mol\n\n")
        f.write(f"fwd-only : \u0394G_bound={dG_b_f:+.3f}\u00b1{err_b_f:.3f}  "
                f"\u0394G_unbound={dG_u_f:+.3f}\u00b1{err_u_f:.3f}  "
                f"\u0394\u0394G={ddG_f:+.3f}\u00b1{err_f_v:.3f} kJ/mol\n")
        if has_rev:
            f.write(f"rev-only : \u0394G_bound={dG_b_r:+.3f}\u00b1{err_b_r:.3f}  "
                    f"\u0394G_unbound={dG_u_r:+.3f}\u00b1{err_u_r:.3f}  "
                    f"\u0394\u0394G={ddG_r:+.3f}\u00b1{err_r_v:.3f} kJ/mol\n")
            f.write(f"combined : \u0394G_bound={dG_b:+.3f}\u00b1{err_b:.3f}  "
                    f"\u0394G_unbound={dG_u:+.3f}\u00b1{err_u:.3f}  "
                    f"\u0394\u0394G={ddG:+.3f}\u00b1{err:.3f} kJ/mol  \u2190 final\n")
            f.write(f"\nConvergence |\u0394\u0394G_fwd \u2212 \u0394\u0394G_rev| = {abs(ddG_f - ddG_r):.3f} kJ/mol\n")
        f.write(f"\n\u0394\u0394G_binding (final) = {ddG:+.3f} \u00b1 {err:.3f} kJ/mol"
                f"  ({ddG/4.184:+.3f} \u00b1 {err/4.184:.3f} kcal/mol)\n")
    print(f"\nResults saved: {out_file}")

    # ── Plots ─────────────────────────────────────────────────────────────────
    if not args.no_plots:
        print("\nGenerating plots...")
        plot_overlap_matrix(
            mbar_b, os.path.join(base_path, 'mbar_overlap_bound.png'),
            'MBAR Overlap Matrix \u2014 Bound')
        plot_overlap_matrix(
            mbar_u, os.path.join(base_path, 'mbar_overlap_unbound.png'),
            'MBAR Overlap Matrix \u2014 Unbound')
        plot_free_energy_profile(
            mbar_b, args.temp,
            os.path.join(base_path, 'free_energy_profile_bound.png'),
            'Free Energy Profile \u2014 Bound')
        plot_free_energy_profile(
            mbar_u, args.temp,
            os.path.join(base_path, 'free_energy_profile_unbound.png'),
            'Free Energy Profile \u2014 Unbound')
        plot_convergence(
            u_b_f, u_b_r,
            os.path.join(base_path, 'convergence_bound.png'),
            'Sampling \u2014 Bound')
        plot_convergence(
            u_u_f, u_u_r,
            os.path.join(base_path, 'convergence_unbound.png'),
            'Sampling \u2014 Unbound')
        print(f"  Plots saved to: {base_path}")

    print("\nDone.")
    return True


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description='FEP \u0394\u0394G_binding Analysis (MBAR) \u2014 single-design or batch mode',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('directory',
                        help='Single design dir (contains forward/) OR outputs/ root for batch auto-discovery')
    parser.add_argument('--skip',     type=float, default=SKIP_FRACTION,
                        help='Equilibration skip fraction')
    parser.add_argument('--temp',     type=float, default=TEMPERATURE,
                        help='Temperature in K')
    parser.add_argument('--windows',  type=int,   default=N_WINDOWS,
                        help='Number of lambda windows')
    parser.add_argument('--replicas', type=int,   default=MAX_REPLICAS,
                        help='Maximum replicas to search per state')
    parser.add_argument('--no-plots', action='store_true',
                        help='Skip all plots (faster)')
    parser.add_argument('--force', action='store_true',
                        help='Re-run even if ddG_results.txt already exists')
    args = parser.parse_args()

    top = os.path.abspath(args.directory)
    if not os.path.isdir(top):
        print(f"ERROR: Directory not found: {top}")
        sys.exit(1)

    batch_replica_dirs = find_outer_replicas(top)

    # Batch mode: directory has replicaN/ subdirs but no forward/ at top level
    is_batch = (
        not os.path.isdir(os.path.join(top, 'forward')) and
        bool(batch_replica_dirs)
    )

    if not is_batch:
        # ── Single-design mode ─────────────────────────────────────────────
        if not args.force and is_analysis_done(top):
            print("Already done (ddG_results.txt exists). Use --force to re-run.")
            sys.exit(0)
        ok = analyze_one(top, args)
        sys.exit(0 if ok else 1)

    # ── Batch mode ──────────────────────────────────────────────────────────
    designs = find_designs_with_data(top)
    if not designs:
        print(f"No designs with XVG data found under: {top}")
        sys.exit(1)

    n_pending = sum(1 for _, p in designs if args.force or not is_analysis_done(p))
    print(f"Batch mode: {len(designs)} design(s) with data  |  "
          f"{len(designs) - n_pending} already done  |  {n_pending} to run")
    if not args.force:
        print("  (use --force to re-run completed designs)\n")

    summary_records = []
    n_ok = n_fail = n_skipped = 0

    for label, design_path in designs:
        if not args.force and is_analysis_done(design_path):
            n_skipped += 1
            ddg_line = extract_final_ddg_line(os.path.join(design_path, 'ddG_results.txt'))
            summary_records.append({
                'label': label,
                'status': 'skipped',
                'result': ddg_line,
                'design_path': design_path,
            })
            print(f"[SKIP] {label}")
            continue

        print(f"\n{'=' * 70}")
        print(f"[{n_ok + n_fail + n_skipped + 1}/{len(designs)}] {label}")
        try:
            ok = analyze_one(design_path, args)
        except Exception as e:
            print(f"EXCEPTION: {e}")
            ok = False

        if ok:
            n_ok += 1
            ddg_line = extract_final_ddg_line(os.path.join(design_path, 'ddG_results.txt'))
            summary_records.append({
                'label': label,
                'status': 'ok',
                'result': ddg_line,
                'design_path': design_path,
            })
        else:
            n_fail += 1
            summary_records.append({
                'label': label,
                'status': 'failed',
                'result': 'FAILED',
                'design_path': design_path,
            })

    update_batch_summary_table(top, summary_records)

    # ── Batch summary ──────────────────────────────────────────────────────
    print(f"\n{'=' * 70}")
    print(f"BATCH SUMMARY  ({n_ok} succeeded  |  {n_fail} failed  |  {n_skipped} skipped)")
    print(f"{'=' * 70}")
    for record in sorted(summary_records, key=lambda item: summary_sort_key(item['label'])):
        label = record['label']
        line = record['result']
        if record['status'] == 'skipped':
            line = f"[skip] {line}"
        print(f"  {label:<50s}  {line}")
    print(f"{'=' * 70}")
    sys.exit(0 if n_fail == 0 else 1)


if __name__ == '__main__':
    main()
