#!/usr/bin/env python3
"""
FEP ΔΔG_binding Analysis - MBAR Method with Visualization

Directory structure (generated by setup_fep.sh + submit_fep.sh):

    <base_path>/
    ├── forward/
    │   ├── bound_R1/lambda{0..31}/PROD/prod.xvg
    │   ├── bound_R2/lambda{0..31}/PROD/prod.xvg
    │   ├── bound_R3/lambda{0..31}/PROD/prod.xvg
    │   ├── unbound_R1/lambda{0..31}/PROD/prod.xvg
    │   ├── unbound_R2/lambda{0..31}/PROD/prod.xvg
    │   └── unbound_R3/lambda{0..31}/PROD/prod.xvg
    └── reverse/          [optional; improves MBAR accuracy when available]
        ├── bound_R{1..N}/lambda{0..31}/PROD/prod.xvg
        └── unbound_R{1..N}/lambda{0..31}/PROD/prod.xvg

Usage:
    python analyze_fep.py /path/to/outputs/design_name
    python analyze_fep.py /path/to/outputs/design_name --skip 0.2
    python analyze_fep.py /path/to/outputs/design_name --no-plots
"""

import os
import sys
import argparse
import warnings
import logging

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

warnings.filterwarnings('ignore')
logging.basicConfig(level=logging.CRITICAL)
for _lg in ['alchemlyb', 'pymbar', 'alchemlyb.estimators', 'pymbar.mbar',
            'alchemlyb.preprocessing', 'alchemlyb.estimators.mbar']:
    logging.getLogger(_lg).setLevel(logging.CRITICAL)

from alchemlyb.parsing.gmx import extract_u_nk
from alchemlyb.preprocessing import subsampling
from alchemlyb.estimators import MBAR
from alchemlyb.visualisation import plot_mbar_overlap_matrix

# Physical constants
R_KJ = 8.314e-3   # kJ/(mol·K)

# Defaults (overridable via CLI)
TEMPERATURE   = 310
SKIP_FRACTION = 0.1
N_WINDOWS     = 32
MAX_REPLICAS  = 3

# ──────────────────────────────────────────────────────────────────────────────
# Data discovery & loading
# ──────────────────────────────────────────────────────────────────────────────

def find_dhdl_files(base_path, direction, state, n_windows, max_replicas):
    """Find prod.xvg (or dhdl.xvg) for every lambda window across all replicas.

    Actual path: <base_path>/<direction>/<state>_R<n>/lambda<w>/PROD/prod.xvg

    Returns:
        list of (replica_id, window_idx, absolute_file_path)
    """
    found = []
    for replica in range(1, max_replicas + 1):
        state_dir = os.path.join(base_path, direction, f"{state}_R{replica}")
        if not os.path.isdir(state_dir):
            continue
        for win in range(n_windows):
            # Priority: PROD/prod.xvg → PROD/dhdl.xvg → dhdl.xvg (fallback)
            candidates = [
                os.path.join(state_dir, f"lambda{win}", "PROD", "prod.xvg"),
                os.path.join(state_dir, f"lambda{win}", "PROD", "dhdl.xvg"),
                os.path.join(state_dir, f"lambda{win}", "dhdl.xvg"),
            ]
            for fpath in candidates:
                if os.path.isfile(fpath) and os.path.getsize(fpath) > 0:
                    found.append((replica, win, fpath))
                    break
    return found


def load_u_nk_from_files(file_entries, T, skip_frac, label=""):
    """Load, trim equilibration, and decorrelate u_nk from file list.

    Args:
        file_entries: list of (replica, win, path)
    Returns:
        concatenated u_nk DataFrame, or None on total failure
    """
    u_nk_list = []
    n_ok = n_fail = 0
    failed_ids = []
    for replica, win, fpath in file_entries:
        try:
            u_nk = extract_u_nk(fpath, T=T)
            if len(u_nk) > 100:
                u_nk = u_nk.iloc[int(len(u_nk) * skip_frac):]
            u_nk = subsampling.decorrelate_u_nk(u_nk)
            u_nk_list.append(u_nk)
            n_ok += 1
        except Exception as e:
            failed_ids.append(f"R{replica}/lambda{win}")
            n_fail += 1

    if label:
        status = f"{n_ok}/{len(file_entries)} windows OK"
        if n_fail:
            status += f", {n_fail} FAILED: {', '.join(failed_ids[:5])}"
            if len(failed_ids) > 5:
                status += f" (+{len(failed_ids)-5} more)"
        print(f"    {label}: {status}")
    return pd.concat(u_nk_list) if u_nk_list else None


def load_state_data(base_path, state, n_windows, max_replicas, skip_frac, T):
    """Load u_nk for one thermodynamic state across all replicas and directions.

    Returns:
        (u_nk_fwd, u_nk_rev)  — u_nk_rev is None when reverse runs not available
    """
    fwd_files = find_dhdl_files(base_path, 'forward', state, n_windows, max_replicas)
    rev_files = find_dhdl_files(base_path, 'reverse', state, n_windows, max_replicas)

    n_fwd_rep = len(set(r for r, _, _ in fwd_files))
    rev_note  = (f"{len(rev_files)} files ({len(set(r for r,_,_ in rev_files))} rep)"
                 if rev_files else "none")
    print(f"  {state.upper():8s}  fwd: {len(fwd_files)} files ({n_fwd_rep} rep)  "
          f"rev: {rev_note}")

    u_nk_fwd = load_u_nk_from_files(fwd_files, T, skip_frac, label="    fwd") \
               if fwd_files else None
    u_nk_rev = load_u_nk_from_files(rev_files, T, skip_frac, label="    rev") \
               if rev_files else None

    return u_nk_fwd, u_nk_rev


# ──────────────────────────────────────────────────────────────────────────────
# MBAR calculation
# ──────────────────────────────────────────────────────────────────────────────

def calc_mbar(u_nk_fwd, u_nk_rev, T):
    """Fit MBAR on combined forward (+ optionally reverse) u_nk data.

    MBAR output delta_f_ is in kT (reduced units).
    We convert to kJ/mol by multiplying by R*T.

    Returns:
        (dG_kJmol, err_kJmol, mbar_obj)   — mbar_obj.delta_f_ still in kT
    """
    if u_nk_fwd is None:
        return None, None, None

    if u_nk_rev is not None:
        combined = pd.concat([u_nk_fwd, u_nk_rev])
        mode = f"bidir  {len(u_nk_fwd)}+{len(u_nk_rev)} samples"
    else:
        combined = u_nk_fwd
        mode = f"fwd-only  {len(u_nk_fwd)} samples"

    mbar = MBAR()
    mbar.fit(combined)

    # Convert kT → kJ/mol  (kBT = R * T  e.g. 2.577 kJ/mol at 310 K)
    kBT = R_KJ * T
    dG  = float(mbar.delta_f_.iloc[0, -1])  * kBT
    err = float(mbar.d_delta_f_.iloc[0, -1]) * kBT

    print(f"    ΔG = {dG:+.2f} ± {err:.2f} kJ/mol  "
          f"({dG/4.184:+.2f} ± {err/4.184:.2f} kcal/mol)  [{mode}]")
    return dG, err, mbar


# ──────────────────────────────────────────────────────────────────────────────
# Plotting
# ──────────────────────────────────────────────────────────────────────────────

def plot_overlap_matrix(mbar, output_path, title):
    try:
        ax = plot_mbar_overlap_matrix(mbar.overlap_matrix)
        ax.set_title(title, fontsize=13, fontweight='bold')
        ax.figure.savefig(output_path, dpi=300, bbox_inches='tight')
        plt.close(ax.figure)
        print(f"  Saved: {output_path}")
    except Exception as e:
        print(f"  WARNING: overlap matrix plot failed: {e}")


def plot_free_energy_profile(mbar, T, output_path, title):
    """Plot ΔF profile in kJ/mol (converting from kT stored in mbar)."""
    try:
        kBT = R_KJ * T
        free_energies = mbar.delta_f_.iloc[0, :] * kBT
        errors        = mbar.d_delta_f_.iloc[0, :] * kBT
        n = len(free_energies)

        fig, ax = plt.subplots(figsize=(10, 6))
        ax.errorbar(range(n), free_energies, yerr=errors,
                    marker='o', markersize=7, linewidth=2, capsize=4,
                    color='#2E86AB', ecolor='#A23B72', capthick=2)
        ax.set_title(title, fontsize=13, fontweight='bold')
        ax.set_xlabel('Lambda state index', fontsize=12)
        ax.set_ylabel('ΔF (kJ/mol)', fontsize=12)
        ax.set_xticks(range(0, n, max(1, n // 8)))
        ax.grid(alpha=0.3, linestyle='--')
        ax.axhline(y=0, color='gray', linestyle='--', linewidth=1)
        fig.tight_layout()
        fig.savefig(output_path, dpi=300, bbox_inches='tight')
        plt.close(fig)
        print(f"  Saved: {output_path}")
    except Exception as e:
        print(f"  WARNING: free energy profile plot failed: {e}")
        import traceback; traceback.print_exc()


def plot_convergence(u_nk_fwd, u_nk_rev, output_path, title):
    try:
        n_fwd = len(u_nk_fwd)
        n_rev = len(u_nk_rev) if u_nk_rev is not None else 0

        fig, axes = plt.subplots(1, 2, figsize=(12, 5))

        # Panel 1: sample counts
        if n_rev > 0:
            labels = ['Forward', 'Reverse', 'Total']
            counts = [n_fwd, n_rev, n_fwd + n_rev]
            colors = ['#2E86AB', '#A23B72', '#44803F']
        else:
            labels = ['Forward (only)', 'Total']
            counts = [n_fwd, n_fwd]
            colors = ['#2E86AB', '#44803F']

        bars = axes[0].bar(labels, counts, color=colors, alpha=0.8, edgecolor='black')
        axes[0].set_ylabel('Decorrelated samples')
        axes[0].set_title('Sample statistics')
        axes[0].grid(alpha=0.3, linestyle='--', axis='y')
        for bar, cnt in zip(bars, counts):
            axes[0].text(bar.get_x() + bar.get_width() / 2, bar.get_height(),
                         str(cnt), ha='center', va='bottom', fontsize=10, fontweight='bold')

        # Panel 2: fwd/rev ratio
        ratio = n_fwd / n_rev if n_rev > 0 else float('inf')
        display_ratio = min(ratio, 5.0)
        axes[1].bar(['Fwd/Rev\nratio'], [display_ratio],
                    color='#F18F01', alpha=0.8, edgecolor='black')
        axes[1].axhline(1.0, color='green', linestyle='--', linewidth=2, label='Ideal: 1.0')
        axes[1].set_ylim(0, max(3.0, display_ratio * 1.2))
        axes[1].set_title('Forward/Reverse balance')
        axes[1].legend()
        note = f'{ratio:.2f}' if ratio != float('inf') else 'fwd only'
        axes[1].text(0, display_ratio, note,
                     ha='center', va='bottom', fontsize=11, fontweight='bold')

        fig.suptitle(title, fontsize=13, fontweight='bold')
        fig.tight_layout()
        fig.savefig(output_path, dpi=300, bbox_inches='tight')
        plt.close(fig)
        print(f"  Saved: {output_path}")
    except Exception as e:
        print(f"  WARNING: convergence plot failed: {e}")


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description='FEP ΔΔG_binding Analysis (MBAR)',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('directory',
                        help='Design output directory (e.g., outputs/design_name)')
    parser.add_argument('--skip',     type=float, default=SKIP_FRACTION,
                        help='Equilibration skip fraction')
    parser.add_argument('--temp',     type=float, default=TEMPERATURE,
                        help='Temperature in K')
    parser.add_argument('--windows',  type=int,   default=N_WINDOWS,
                        help='Number of lambda windows')
    parser.add_argument('--replicas', type=int,   default=MAX_REPLICAS,
                        help='Maximum replicas to search per state')
    parser.add_argument('--no-plots', action='store_true',
                        help='Skip all plots (faster)')
    args = parser.parse_args()

    base_path = os.path.abspath(args.directory)
    if not os.path.isdir(base_path):
        print(f"ERROR: Directory not found: {base_path}")
        sys.exit(1)

    print("=" * 70)
    print(f"FEP ΔΔG Analysis  |  {base_path}")
    print(f"T = {args.temp} K  |  skip {args.skip*100:.0f}%  |  "
          f"{args.windows} windows  |  max {args.replicas} replicas")
    print("=" * 70)

    # ── Load data ──────────────────────────────────────────────────────────────
    print("\nLoading data...")
    u_b_f, u_b_r = load_state_data(base_path, 'bound',
                                    args.windows, args.replicas, args.skip, args.temp)
    u_u_f, u_u_r = load_state_data(base_path, 'unbound',
                                    args.windows, args.replicas, args.skip, args.temp)

    if u_b_f is None:
        print("ERROR: No BOUND forward data. Check directory structure.")
        sys.exit(1)
    if u_u_f is None:
        print("ERROR: No UNBOUND forward data. Check directory structure.")
        sys.exit(1)

    # ── MBAR ───────────────────────────────────────────────────────────────────
    print("\nFitting MBAR...")
    print("  BOUND state:")
    dG_b, err_b, mbar_b = calc_mbar(u_b_f, u_b_r, args.temp)

    print("  UNBOUND state:")
    dG_u, err_u, mbar_u = calc_mbar(u_u_f, u_u_r, args.temp)

    if dG_b is None or dG_u is None:
        print("\nERROR: MBAR calculation failed.")
        sys.exit(1)

    # ── ΔΔG ───────────────────────────────────────────────────────────────────
    ddG = dG_b - dG_u
    err = np.sqrt(err_b**2 + err_u**2)

    print("\n" + "=" * 70)
    print("FINAL RESULTS")
    print("=" * 70)
    print(f"ΔG_bound    = {dG_b:+8.2f} ± {err_b:.2f} kJ/mol"
          f"  ({dG_b/4.184:+7.2f} ± {err_b/4.184:.2f} kcal/mol)")
    print(f"ΔG_unbound  = {dG_u:+8.2f} ± {err_u:.2f} kJ/mol"
          f"  ({dG_u/4.184:+7.2f} ± {err_u/4.184:.2f} kcal/mol)")
    print("-" * 70)
    print(f"ΔΔG_binding = {ddG:+7.2f} ± {err:.2f} kJ/mol"
          f"  ({ddG/4.184:+6.2f} ± {err/4.184:.2f} kcal/mol)")
    print("=" * 70)

    if   ddG >  2.0:
        print(f"\n  ΔΔG = {ddG:+.1f} kJ/mol  → Mutation WEAKENS binding")
    elif ddG < -2.0:
        print(f"\n  ΔΔG = {ddG:+.1f} kJ/mol  → Mutation STRENGTHENS binding")
    else:
        print(f"\n  ΔΔG ≈ {ddG:+.1f} kJ/mol  → No significant effect (within ±2 kJ/mol)")

    # ── Save results ───────────────────────────────────────────────────────────
    out_file = os.path.join(base_path, 'ddG_results.txt')
    with open(out_file, 'w', encoding='utf-8') as f:
        f.write("FEP ΔΔG_binding Analysis Results (MBAR)\n")
        f.write("=" * 70 + "\n\n")
        f.write(f"Directory:   {base_path}\n")
        f.write(f"Temperature: {args.temp} K\n")
        f.write(f"Skip:        {args.skip:.1%}\n")
        f.write(f"kBT:         {R_KJ * args.temp:.4f} kJ/mol\n\n")
        f.write(f"ΔG_bound    = {dG_b:+.3f} ± {err_b:.3f} kJ/mol"
                f"  ({dG_b/4.184:+.3f} ± {err_b/4.184:.3f} kcal/mol)\n")
        f.write(f"ΔG_unbound  = {dG_u:+.3f} ± {err_u:.3f} kJ/mol"
                f"  ({dG_u/4.184:+.3f} ± {err_u/4.184:.3f} kcal/mol)\n\n")
        f.write(f"ΔΔG_binding = {ddG:+.3f} ± {err:.3f} kJ/mol"
                f"  ({ddG/4.184:+.3f} ± {err/4.184:.3f} kcal/mol)\n")
    print(f"\nResults saved: {out_file}")

    # ── Plots ─────────────────────────────────────────────────────────────────
    if not args.no_plots:
        print("\nGenerating plots...")
        plot_overlap_matrix(
            mbar_b, os.path.join(base_path, 'mbar_overlap_bound.png'),
            'MBAR Overlap Matrix — Bound')
        plot_overlap_matrix(
            mbar_u, os.path.join(base_path, 'mbar_overlap_unbound.png'),
            'MBAR Overlap Matrix — Unbound')
        plot_free_energy_profile(
            mbar_b, args.temp,
            os.path.join(base_path, 'free_energy_profile_bound.png'),
            'Free Energy Profile — Bound')
        plot_free_energy_profile(
            mbar_u, args.temp,
            os.path.join(base_path, 'free_energy_profile_unbound.png'),
            'Free Energy Profile — Unbound')
        plot_convergence(
            u_b_f, u_b_r,
            os.path.join(base_path, 'convergence_bound.png'),
            'Sampling — Bound')
        plot_convergence(
            u_u_f, u_u_r,
            os.path.join(base_path, 'convergence_unbound.png'),
            'Sampling — Unbound')
        print(f"  Plots saved to: {base_path}")

    print("\nDone.")


if __name__ == '__main__':
    main()
